language: rust
cache: cargo

jobs:
  include:
    - stage: test
      name: "Unit Tests"
      rust: stable
      script:
        - cargo test
    - stage: test
      name: "Format Check"
      rust: stable
      before_script:
        - rustup component add rustfmt-preview
      script:
        - cargo fmt --all -- --check
    - stage: test
      name: "Linting Check"
      rust: nightly
      before_script:
        - rustup component add clippy-preview
      script:
        - cargo clippy
stages:
  - test
