language: rust
rust: 1.31.0
cache: cargo
jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script:
        - cargo test
    - stage: test
      name: "Format Check"
      before_script:
        - rustup component add rustfmt-preview
      script:
        - cargo fmt --all -- --check
    - stage: test
      name: "Linting Check"
      before_script:
        - rustup component add clippy-preview
      script:
        - cargo clippy
stages:
  - test
