[package]
authors = ["IML Team <iml@whamcloud.com>"]
description = "Scrapes Lustre stats and aggregates into JSON or YAML"
edition = "2018"
license = "MIT"
name = "lustre_collector"
version = "0.4.0"

[dependencies]
clap = "2.33"
combine = "=4.6.2"
serde = {version = "1", features = ["derive"]}
serde_json = "1.0"
serde_yaml = "0.8"

[dev-dependencies]
insta = "1"

[profile.release]
lto = true
