[package]
name = "lustre_collector"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
combine = "3.8.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
clap = "2.33"

[dependencies.error-chain]
version = "0.12"
default-features = false

[dev-dependencies]
pretty_assertions = "0.6"
insta = "0.10"

[profile.release]
lto = true
