[package]
name = "lustre_collector"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]

[dependencies]
combine = "3.5.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8.4"
clap = "2.32.0"

[dependencies.error-chain]
version = "0.12.0"
default-features = false

[dev-dependencies]
pretty_assertions = "0.5"

[profile.release]
lto = true
