[package]
name = "lustre_collector"
version = "0.2.12"
license = "MIT"
description = "Scrapes Lustre stats and aggregates into JSON or YAML"
authors = ["IML Team <iml@whamcloud.com>"]
edition = "2018"

[dependencies]
combine = "4.0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
clap = "2.33"

[dev-dependencies]
insta = "0.15"

[profile.release]
lto = true
