[package]
name = "lustre_collector"
version = "0.1.0"
authors = ["IML Team <iml@whamcloud.com>"]

[dependencies]
combine = "3.5.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8.3"

[dev-dependencies]
pretty_assertions = "0.5"

[profile.release]
lto = true
